# Generated by Django 5.2.16 on 2026-08-04 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='koc',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koc',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=250, verbose_name='Tên người nhận')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Số điện thoại chưa đúng định dạng', regex='^(0|\\+84)\\d{9}$')], verbose_name='Số điện thoại')),
                ('province', models.CharField(max_length=150, verbose_name='Thành Phố/Tỉnh')),
                ('ward', models.CharField(max_length=150, verbose_name='Xã')),
                ('address_detail', models.CharField(max_length=250, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default'],
            },
        ),
    ]
