# Generated by Django 5.2.16 on 2026-08-04 09:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_farmer_created_date_farmer_updated_date_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=100, verbose_name='Nền tảng')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Tiêu đề')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('post_url', models.URLField(blank=True, max_length=500, verbose_name='Đường dẫn bài đăng')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã đăng'), ('HIDDEN', 'Đã ẩn')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã liên kết')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt nhấp')),
                ('koc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_links', to='accounts.koc', verbose_name='KOC')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tỷ lệ hoa hồng')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền hoa hồng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ ghi nhận'), ('APPROVED', 'Đã ghi nhận'), ('PAID', 'Đã thanh toán')], default='PENDING', max_length=20, verbose_name='Trạng thái hoa hồng')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('affiliate_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.affiliatelink', verbose_name='Liên kết quảng bá')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
