# Generated by Django 5.2.16 on 2026-08-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='orders.orderitem', verbose_name='Sản phẩm trong đơn hàng'),
        ),
        migrations.AddField(
            model_name='promotionpost',
            name='affiliate_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_posts', to='affiliates.affiliatelink', verbose_name='Liên kết quảng bá'),
        ),
        migrations.AddConstraint(
            model_name='affiliatelink',
            constraint=models.UniqueConstraint(fields=('koc', 'product'), name='unique_koc_product_affiliate_link'),
        ),
    ]
