# Generated by Django 5.2.16 on 2026-08-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatelink',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='promotionpost',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='promotionpost',
            name='post_url',
        ),
        migrations.RemoveField(
            model_name='promotionpost',
            name='title',
        ),
    ]
