# Generated by Django 5.2.16 on 2026-08-22 13:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_remove_affiliatelink_click_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Nội dung media')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Hình ảnh'), ('VIDEO', 'Video')], max_length=10, verbose_name='Loại media')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('promotion_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='affiliates.promotionpost', verbose_name='Bài quảng bá')),
            ],
            options={
                'ordering': ['display_order', 'created_date'],
            },
        ),
    ]
