# Generated by Django 5.2.16 on 2026-08-04 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('ACCOUNT', 'Tài khoản'), ('ORDER', 'Đơn hàng'), ('PAYMENT', 'Thanh toán'), ('COMMISSION', 'Hoa hồng'), ('SYSTEM', 'Hệ thống')], default='SYSTEM', max_length=20, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=250, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu liên quan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
