# Generated by Django 5.2.16 on 2026-09-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushDevice',
        ),
    ]
