# Generated by Django 5.2.16 on 2026-08-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
    ]
