# Generated by Django 5.2.16 on 2026-08-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_initial'),
        ('orders', '0002_remove_order_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='affiliate_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='affiliates.affiliatelink', verbose_name='Liên kết giới thiệu'),
        ),
    ]
