# Generated by Django 5.2.16 on 2026-08-04 09:19

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_farmer_created_date_farmer_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên đơn vị')),
                ('symbol', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Số lượng đặt tối thiểu')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Ngày thu hoạch')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING', 'Chờ kiểm tra'), ('AVAILABLE', 'Đang bán'), ('HIDDEN', 'Đã ẩn'), ('REJECTED', 'Không đạt yêu cầu')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do không đạt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.farmer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unit')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Ảnh sản phẩm')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'created_date'],
            },
        ),
        migrations.CreateModel(
            name='ImageQualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('raw_blur_score', models.FloatField(blank=True, null=True)),
                ('normalized_blur_score', models.FloatField(blank=True, null=True, verbose_name='Điểm độ mờ chuẩn hóa')),
                ('brightness_mean', models.FloatField(blank=True, null=True, verbose_name='Độ sáng trung bình')),
                ('contrast_std', models.FloatField(blank=True, null=True, verbose_name='Độ tương phản')),
                ('dark_ratio', models.FloatField(blank=True, null=True, verbose_name='Tỷ lệ vùng tối')),
                ('bright_ratio', models.FloatField(blank=True, null=True, verbose_name='Tỷ lệ vùng sáng')),
                ('is_blurry', models.BooleanField(default=False, verbose_name='Ảnh bị mờ')),
                ('is_too_dark', models.BooleanField(default=False, verbose_name='Ảnh quá tối')),
                ('is_too_bright', models.BooleanField(default=False, verbose_name='Ảnh quá sáng')),
                ('is_acceptable', models.BooleanField(default=False, verbose_name='Ảnh đạt yêu cầu')),
                ('feedback', models.TextField(blank=True, verbose_name='Hướng dẫn chụp lại')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_result', to='products.productimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
