# Generated by Django 5.2.16 on 2026-09-03 12:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số lượng đặt tối thiểu'),
        ),
    ]
