# Generated by Django 5.2.16 on 2026-08-04 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao đánh giá')),
                ('comment', models.TextField(blank=True, verbose_name='Nội dung đánh giá')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.orderitem', verbose_name='Sản phẩm đã mua')),
            ],
            options={
                'ordering': ['-created_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
