# Generated by Django 5.2.16 on 2026-08-04 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('ONLINE', 'Thanh toán trực tuyến')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền thanh toán')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('transaction_code', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
